import { BusinessCategory } from '../business/business.schema';

export const defaultServiceCategories = [
  {
    name: 'Beauty & Grooming',
    slug: 'beauty-grooming',
    businessCategory: BusinessCategory.SALON,
    description: 'Salons, grooming studios, spa treatments, and personal care.',
    icon: 'sparkles',
    keywords: ['salon', 'haircut', 'spa', 'grooming', 'beauty'],
    displayOrder: 10,
  },
  {
    name: 'Fitness & Wellness',
    slug: 'fitness-wellness',
    businessCategory: BusinessCategory.GYM,
    description: 'Gyms, trainers, yoga, recovery, and wellness sessions.',
    icon: 'dumbbell',
    keywords: ['gym', 'fitness', 'yoga', 'trainer', 'wellness'],
    displayOrder: 20,
  },
  {
    name: 'Health & Clinics',
    slug: 'health-clinics',
    businessCategory: BusinessCategory.CLINIC,
    description: 'Clinics, checkups, consultations, and local health providers.',
    icon: 'stethoscope',
    keywords: ['clinic', 'doctor', 'health', 'consultation'],
    displayOrder: 30,
  },
  {
    name: 'Home Repairs',
    slug: 'home-repairs',
    businessCategory: BusinessCategory.REPAIR,
    description: 'Repair specialists for appliances, plumbing, electrical, and maintenance.',
    icon: 'wrench',
    keywords: ['repair', 'plumbing', 'electrician', 'maintenance'],
    displayOrder: 40,
  },
  {
    name: 'Food & Dining',
    slug: 'food-dining',
    businessCategory: BusinessCategory.RESTAURANT,
    description: 'Restaurants, cafes, meal services, and local dining experiences.',
    icon: 'utensils',
    keywords: ['restaurant', 'food', 'dining', 'cafe'],
    displayOrder: 50,
  },
  {
    name: 'Learning & Tuition',
    slug: 'learning-tuition',
    businessCategory: BusinessCategory.TUITION,
    description: 'Tutors, coaching, classes, and skill-building sessions.',
    icon: 'graduation-cap',
    keywords: ['tuition', 'classes', 'tutor', 'learning'],
    displayOrder: 60,
  },
];

export const defaultServiceCollections = [
  {
    title: 'Glow-up appointments',
    slug: 'glow-up-appointments',
    subtitle: 'Highly rated salons and personal care studios.',
    description: 'Book hair, grooming, spa, and beauty services from trusted local vendors.',
    icon: 'sparkles',
    categories: [BusinessCategory.SALON],
    keywords: ['haircut', 'salon', 'beauty', 'spa'],
    accent: 'rose',
    displayOrder: 10,
  },
  {
    title: 'Move better this week',
    slug: 'move-better-this-week',
    subtitle: 'Fitness, training, wellness, and recovery nearby.',
    description: 'Explore gyms and wellness providers with bookable sessions.',
    icon: 'activity',
    categories: [BusinessCategory.GYM],
    keywords: ['fitness', 'gym', 'yoga', 'trainer'],
    accent: 'gold',
    displayOrder: 20,
  },
  {
    title: 'Fix it fast',
    slug: 'fix-it-fast',
    subtitle: 'Reliable repair experts for urgent home and device work.',
    description: 'Find repair vendors with clear prices and quick slots.',
    icon: 'wrench',
    categories: [BusinessCategory.REPAIR],
    keywords: ['repair', 'plumbing', 'electrician', 'maintenance'],
    accent: 'clay',
    displayOrder: 30,
  },
  {
    title: 'Care close to home',
    slug: 'care-close-to-home',
    subtitle: 'Clinics and health services around your area.',
    description: 'Discover clinics and local providers for consultations and checkups.',
    icon: 'heart-pulse',
    categories: [BusinessCategory.CLINIC],
    keywords: ['clinic', 'doctor', 'health', 'consultation'],
    accent: 'sage',
    displayOrder: 40,
  },
  {
    title: 'Weekend essentials',
    slug: 'weekend-essentials',
    subtitle: 'Dining, self-care, and quick services for the weekend.',
    description: 'A mixed collection of popular local vendors for easy weekend planning.',
    icon: 'calendar-heart',
    categories: [BusinessCategory.RESTAURANT, BusinessCategory.SALON, BusinessCategory.GYM],
    keywords: ['restaurant', 'salon', 'fitness', 'weekend'],
    accent: 'burgundy',
    displayOrder: 50,
  },
];
